from gym_fuzz1ng.envs.fuzz_token_base_env import FuzzTokenBaseEnv
from gym_fuzz1ng.envs.fuzz_word_base_env import FuzzWordBaseEnv

from gym_fuzz1ng.envs.fuzz_libpng_env import FuzzTokenLibPNGEnv
from gym_fuzz1ng.envs.fuzz_libpng_env import FuzzWordLibPNGEnv

from gym_fuzz1ng.envs.fuzz_simple_bits_env import FuzzTokenSimpleBitsEnv
from gym_fuzz1ng.envs.fuzz_simple_bits_env import FuzzWordSimpleBitsEnv
